name: CI - Lint and Test

on:
  push:
    branches: [ main, master, develop, beta ]
  pull_request:
    branches: [ main, master, develop, beta ]

permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # =============================================================================
  # Lint and Format Check
  # =============================================================================
  lint:
    name: Lint and Format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  # =============================================================================
  # Test Suite
  # =============================================================================
  test:
    name: Test Suite
    runs-on: ubuntu-24.04
    
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: sockudo
          MYSQL_USER: sockudo
          MYSQL_PASSWORD: sockudo123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev libpq-dev libmariadb-dev cmake mysql-client
      
      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysql -h 127.0.0.1 -u root -proot123 -e "SELECT 1" &> /dev/null; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL... ($i/30)"
            sleep 2
          done
      
      - name: Initialize MySQL database
        run: |
          mysql -h 127.0.0.1 -u root -proot123 sockudo < ./sql/init-sql.sql

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo test --verbose --all-features
        env:
          REDIS_URL: redis://localhost:6379

  # =============================================================================
  # Security Audit
  # =============================================================================
  security:
    name: Security Audit
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Security audit
        run: cargo audit

  # =============================================================================
  # Manual Build Instructions (PR only)
  # =============================================================================
  manual-build-info:
    name: 🔨 Manual Build Instructions
    runs-on: ubuntu-24.04
    needs: [lint, test, security]
    steps:
      - name: Post build instructions
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Starting manual build info job...');
            console.log('Event name:', context.eventName);
            
            const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/workflows/manual-build.yml`;
            let prNumber, branchName;
            
            if (context.eventName === 'pull_request') {
              prNumber = context.payload.pull_request.number;
              branchName = context.payload.pull_request.head.ref;
            } else if (context.eventName === 'push') {
              // For push events, try to find the associated PR
              branchName = context.ref.replace('refs/heads/', '');
              const prs = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: `${context.repo.owner}:${branchName}`,
                state: 'open'
              });
              if (prs.data.length > 0) {
                prNumber = prs.data[0].number;
              }
            }
            
            if (!prNumber) {
              console.log('No PR found for this push, skipping');
              return;
            }
            
            console.log('PR number:', prNumber);
            console.log('Branch name:', branchName);
            console.log('Run URL:', runUrl);
            
            // Check if we've already posted instructions
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });
            
            console.log(`Found ${comments.data.length} existing comments`);
            
            const existingComment = comments.data.find(comment => 
              comment.user.login === 'github-actions[bot]' && 
              comment.body.includes('Manual Build Available')
            );
            
            console.log('Existing comment found:', !!existingComment);
            
            if (!existingComment) {
              const body = [
                '## 🔨 Manual Build Available',
                '',
                '**To build artifacts for this PR:**',
                '',
                `1. **Click here:** [🚀 Trigger Manual Build](${runUrl})`,
                '2. Click **"Run workflow"** (green button)',
                `3. Select branch: \`${branchName}\``,
                '4. Choose platforms to build:',
                '   - ☑️ Linux x64 (GNU)',
                '   - ☑️ macOS x64 (Intel)',
                '   - ☑️ macOS ARM64 (Apple Silicon)',
                '   - ☑️ Windows x64',
                '   - ☑️ Docker image',
                '5. Click **"Run workflow"**',
                '',
                '**Artifacts will be posted here when build completes** ⬇️',
                '',
                '---',
                '*This comment will be updated with download links once builds are triggered*'
              ].join('\n');
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: body
              });
              
              console.log('Posted manual build instructions to PR');
            } else {
              console.log('Manual build instructions already posted, skipping');
            }