name: CI - Lint and Test

on:
  push:
    branches: [ main, master, develop, beta ]
  pull_request:
    branches: [ main, master, develop, beta ]

permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # =============================================================================
  # Lint and Format Check
  # =============================================================================
  lint:
    name: Lint and Format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  # =============================================================================
  # Test Suite
  # =============================================================================
  test:
    name: Test Suite
    runs-on: ubuntu-24.04
    
    services:
      # Single Redis instance for basic tests
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      # Redis test instance matching docker-compose.test.yml
      redis-test:
        image: redis:7-alpine
        ports:
          - 16379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 15s
          --health-timeout 5s
          --health-retries 2
      
      # Redis Cluster for horizontal adapter tests
      redis-cluster:
        image: grokzen/redis-cluster:7.0.10
        env:
          IP: 0.0.0.0
          INITIAL_PORT: 7003
          MASTERS: 3
          SLAVES_PER_MASTER: 0
        ports:
          - 7001:7001
          - 7002:7002
          - 7003:7003
      
      # NATS cluster node 1
      nats-1:
        image: nats:alpine
        ports:
          - 14222:4222
          - 18222:8222
        options: >-
          --name nats-1
          --cluster_name NATS
          --cluster nats://0.0.0.0:6222
          --routes nats://nats-2:6222
          --http_port 8222
      
      # NATS cluster node 2
      nats-2:
        image: nats:alpine
        ports:
          - 14223:4222
          - 18223:8222
        options: >-
          --name nats-2
          --cluster_name NATS
          --cluster nats://0.0.0.0:6222
          --routes nats://nats-1:6222
          --http_port 8222
      
      # MySQL for app management tests
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: sockudo
          MYSQL_USER: sockudo
          MYSQL_PASSWORD: sockudo123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      
      # MySQL test instance matching docker-compose.test.yml
      mysql-test:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: sockudo
          MYSQL_INITDB_SKIP_TZINFO: 1
        ports:
          - 13306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev libpq-dev libmariadb-dev cmake mysql-client
      
      - name: Wait for MySQL instances to be ready
        run: |
          # Wait for main MySQL instance
          for i in {1..30}; do
            if mysql -h 127.0.0.1 -P 3306 -u root -proot123 -e "SELECT 1" &> /dev/null; then
              echo "MySQL (port 3306) is ready!"
              break
            fi
            echo "Waiting for MySQL (port 3306)... ($i/30)"
            sleep 2
          done
          
          # Wait for test MySQL instance
          for i in {1..30}; do
            if mysql -h 127.0.0.1 -P 13306 -u root -proot123 -e "SELECT 1" &> /dev/null; then
              echo "MySQL test (port 13306) is ready!"
              break
            fi
            echo "Waiting for MySQL test (port 13306)... ($i/30)"
            sleep 2
          done
      
      - name: Initialize MySQL databases
        run: |
          # Initialize main MySQL database
          mysql -h 127.0.0.1 -P 3306 -u root -proot123 sockudo < ./sql/init-sql.sql
          
          # Initialize test MySQL database
          mysql -h 127.0.0.1 -P 13306 -u root -proot123 -e "CREATE DATABASE IF NOT EXISTS sockudo;"
          mysql -h 127.0.0.1 -P 13306 -u root -proot123 sockudo < ./sql/init-sql-docker.sql
          mysql -h 127.0.0.1 -P 13306 -u root -proot123 sockudo < ./sql/init-test.sql

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo test --verbose --all-features
        env:
          # Redis configurations
          REDIS_URL: redis://localhost:6379
          DATABASE_REDIS_HOST: localhost
          DATABASE_REDIS_PORT: 16379
          
          # Redis Cluster configuration  
          REDIS_CLUSTER_NODES: localhost:7001,localhost:7002,localhost:7003
          
          # NATS configuration
          NATS_SERVERS: nats://localhost:14222,nats://localhost:14223
          
          # MySQL configurations
          DATABASE_MYSQL_HOST: localhost
          DATABASE_MYSQL_PORT: 13306
          DATABASE_MYSQL_USER: root
          DATABASE_MYSQL_PASSWORD: root123
          DATABASE_MYSQL_DATABASE: sockudo

  # =============================================================================
  # Security Audit
  # =============================================================================
  security:
    name: Security Audit
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Security audit
        run: cargo audit

  # =============================================================================
  # Manual Build Instructions (PR only)
  # =============================================================================
  manual-build-info:
    name: 🔨 Manual Build Instructions
    runs-on: ubuntu-24.04
    needs: [lint, test, security]
    steps:
      - name: Post build instructions
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Starting manual build info job...');
            console.log('Event name:', context.eventName);
            
            const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/workflows/manual-build.yml`;
            let prNumber, branchName;
            
            if (context.eventName === 'pull_request') {
              prNumber = context.payload.pull_request.number;
              branchName = context.payload.pull_request.head.ref;
            } else if (context.eventName === 'push') {
              // For push events, try to find the associated PR
              branchName = context.ref.replace('refs/heads/', '');
              const prs = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: `${context.repo.owner}:${branchName}`,
                state: 'open'
              });
              if (prs.data.length > 0) {
                prNumber = prs.data[0].number;
              }
            }
            
            if (!prNumber) {
              console.log('No PR found for this push, skipping');
              return;
            }
            
            console.log('PR number:', prNumber);
            console.log('Branch name:', branchName);
            console.log('Run URL:', runUrl);
            
            // Check if we've already posted instructions
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });
            
            console.log(`Found ${comments.data.length} existing comments`);
            
            const existingComment = comments.data.find(comment => 
              comment.user.login === 'github-actions[bot]' && 
              comment.body.includes('Manual Build Available')
            );
            
            console.log('Existing comment found:', !!existingComment);
            
            if (!existingComment) {
              const body = [
                '## 🔨 Manual Build Available',
                '',
                '**To build artifacts for this PR:**',
                '',
                `1. **Click here:** [🚀 Trigger Manual Build](${runUrl})`,
                '2. Click **"Run workflow"** (green button)',
                `3. Select branch: \`${branchName}\``,
                '4. Choose platforms to build:',
                '   - ☑️ Linux x64 (GNU)',
                '   - ☑️ macOS x64 (Intel)',
                '   - ☑️ macOS ARM64 (Apple Silicon)',
                '   - ☑️ Windows x64',
                '   - ☑️ Docker image',
                '5. Click **"Run workflow"**',
                '',
                '**Artifacts will be posted here when build completes** ⬇️',
                '',
                '---',
                '*This comment will be updated with download links once builds are triggered*'
              ].join('\n');
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: body
              });
              
              console.log('Posted manual build instructions to PR');
            } else {
              console.log('Manual build instructions already posted, skipping');
            }