name: Manual Build - Cross Platform Artifacts

on:
  workflow_dispatch:
    inputs:
      build_linux_x64:
        description: 'Build Linux x86_64 (GNU + musl)'
        required: false
        type: boolean
        default: false
      build_linux_arm64:
        description: 'Build Linux ARM64 (GNU + musl)'
        required: false
        type: boolean
        default: false
      build_macos_x64:
        description: 'Build macOS x86_64 (Intel)'
        required: false
        type: boolean
        default: false
      build_macos_arm64:
        description: 'Build macOS ARM64 (Apple Silicon)'
        required: false
        type: boolean
        default: false
      build_windows_x64:
        description: 'Build Windows x86_64'
        required: false
        type: boolean
        default: false
      build_docker:
        description: 'Build Docker image'
        required: false
        type: boolean
        default: false
      upload_to_pr:
        description: 'Upload artifacts to PR (if applicable)'
        required: false
        type: boolean
        default: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # =============================================================================
  # Build Binaries using Reusable Workflow
  # =============================================================================
  build-linux-x64-gnu:
    if: inputs.build_linux_x64
    uses: ./.github/workflows/build-binary.yml
    with:
      target_name: Linux x86_64 (GNU)
      target_triple: x86_64-unknown-linux-gnu
      runner_os: ubuntu-24.04
      archive_ext: tgz
      binary_name: sockudo
      artifact_retention_days: 30

  build-linux-x64-musl:
    if: inputs.build_linux_x64
    uses: ./.github/workflows/build-binary.yml
    with:
      target_name: Linux x86_64 (musl)
      target_triple: x86_64-unknown-linux-musl
      runner_os: ubuntu-24.04
      archive_ext: tgz
      binary_name: sockudo
      artifact_retention_days: 30

  build-linux-arm64-gnu:
    if: inputs.build_linux_arm64
    uses: ./.github/workflows/build-binary.yml
    with:
      target_name: Linux ARM64 (GNU)
      target_triple: aarch64-unknown-linux-gnu
      runner_os: ubuntu-24.04-arm
      archive_ext: tgz
      binary_name: sockudo
      artifact_retention_days: 30

  build-linux-arm64-musl:
    if: inputs.build_linux_arm64
    uses: ./.github/workflows/build-binary.yml
    with:
      target_name: Linux ARM64 (musl)
      target_triple: aarch64-unknown-linux-musl
      runner_os: ubuntu-24.04-arm
      archive_ext: tgz
      binary_name: sockudo
      artifact_retention_days: 30


  build-macos-x64:
    if: inputs.build_macos_x64
    uses: ./.github/workflows/build-binary.yml
    with:
      target_name: macOS x86_64
      target_triple: x86_64-apple-darwin
      runner_os: macos-13
      archive_ext: tgz
      binary_name: sockudo
      artifact_retention_days: 30

  build-macos-arm64:
    if: inputs.build_macos_arm64
    uses: ./.github/workflows/build-binary.yml
    with:
      target_name: macOS ARM64
      target_triple: aarch64-apple-darwin
      runner_os: macos-latest
      archive_ext: tgz
      binary_name: sockudo
      artifact_retention_days: 30

  build-windows-x64:
    if: inputs.build_windows_x64
    uses: ./.github/workflows/build-binary.yml
    with:
      target_name: Windows x86_64
      target_triple: x86_64-pc-windows-msvc
      runner_os: windows-latest
      archive_ext: zip
      binary_name: sockudo.exe
      artifact_retention_days: 30

  # =============================================================================
  # Docker Build
  # =============================================================================
  docker:
    name: Docker Build
    runs-on: ubuntu-24.04
    if: inputs.build_docker
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker metadata
        id: meta
        run: |
          if [[ "$GITHUB_REF_NAME" =~ ^[0-9]+/merge$ ]]; then
            # PR merge ref format
            PR_NUM=$(echo "$GITHUB_REF_NAME" | cut -d'/' -f1)
            echo "tags=sockudo:pr-${PR_NUM}" >> $GITHUB_OUTPUT
            echo "archive_name=sockudo-docker-pr-${PR_NUM}" >> $GITHUB_OUTPUT
          else
            # Branch or manual trigger
            SAFE_BRANCH=$(echo "$GITHUB_REF_NAME" | sed 's/[^a-zA-Z0-9._-]/-/g')
            TIMESTAMP=$(date +%Y%m%d-%H%M%S)
            echo "tags=sockudo:${SAFE_BRANCH}-${TIMESTAMP}" >> $GITHUB_OUTPUT
            echo "archive_name=sockudo-docker-${SAFE_BRANCH}-${TIMESTAMP}" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          docker run --rm -d --name sockudo-test -p 6001:6001 \
            -e RUST_LOG=info \
            -e SOCKUDO_DEFAULT_APP_ID=demo-app \
            -e SOCKUDO_DEFAULT_APP_KEY=app-key \
            -e SOCKUDO_DEFAULT_APP_SECRET=app-secret \
            ${{ steps.meta.outputs.tags }}
          sleep 10
          curl -f http://localhost:6001/up/demo-app || exit 1
          docker stop sockudo-test

      - name: Save Docker image
        run: |
          docker save ${{ steps.meta.outputs.tags }} | gzip > ${{ steps.meta.outputs.archive_name }}.tar.gz

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.meta.outputs.archive_name }}
          path: ${{ steps.meta.outputs.archive_name }}.tar.gz
          retention-days: 30

  # =============================================================================
  # Post to PR
  # =============================================================================
  post-to-pr:
    name: Post Results to PR
    runs-on: ubuntu-24.04
    needs: [build-linux-x64-gnu, build-linux-x64-musl, build-linux-arm64-gnu, build-linux-arm64-musl, build-macos-x64, build-macos-arm64, build-windows-x64, docker]
    permissions:
      contents: read
      pull-requests: write
      issues: write
    if: |
      always() && 
      inputs.upload_to_pr &&
      (contains(needs.*.result, 'success'))
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find PR number
        id: pr
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          else
            # Try to find PR for current branch
            PR_NUMBER=$(gh pr list --head ${{ github.ref_name }} --json number --jq '.[0].number' || echo "")
            echo "number=$PR_NUMBER" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Post comment to PR
        if: steps.pr.outputs.number != ''
        uses: actions/github-script@v7
        with:
          script: |
            const artifacts = [];
            
            if ('${{ inputs.build_linux_x64 }}' === 'true') artifacts.push('Linux x64 (GNU + musl)');
            if ('${{ inputs.build_linux_arm64 }}' === 'true') artifacts.push('Linux ARM64 (GNU + musl)');
            if ('${{ inputs.build_macos_x64 }}' === 'true') artifacts.push('macOS x64');
            if ('${{ inputs.build_macos_arm64 }}' === 'true') artifacts.push('macOS ARM64');
            if ('${{ inputs.build_windows_x64 }}' === 'true') artifacts.push('Windows x64');
            if ('${{ inputs.build_docker }}' === 'true') artifacts.push('Docker image');
            
            const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            
            const body = `## 🔨 Manual Build Completed
            
            **Built artifacts:** ${artifacts.join(', ')}
            
            **Workflow run:** [View results](${runUrl})
            
            Artifacts are available for download from the [workflow run page](${runUrl}) for 30 days.
            
            ---
            *Triggered by @${context.actor} via workflow_dispatch*`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.pr.outputs.number }},
              body: body
            });