name: Publish to Crates.io Manually

on:
  workflow_dispatch

permissions:
  contents: write
  packages: write

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io

jobs:
  # =============================================================
  # Publish to Crates.io
  # =============================================================================
  publish-crates:
    name: Publish to Crates.io
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev libpq-dev libmariadb-dev cmake

      - name: Publish to crates.io
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        if: env.CRATES_IO_TOKEN != ''
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}